getsentry/github-workflows

.github/workflows/updater.yml, .github/workflows/workflow-tests.yml, scripts/update-dependency.ps1, tests/update-dependency.ps1
For sentry-react-native update of react-native which also contains tag "latest", but we want a specific version selected.
This feature can also be used to pin to a specific major version, or to avoid pre-releases, if those are tagged in a repository, etc.
=> feat: support version pattern matching

.github/workflows/updater.yml
This PR adds the following outputs to the update workflow:
- url
- original tag
- latest tag
- base branch
- pr branch
This way, other repositories can pick up the created PR and amend it as they see fit. 
An example can be seen here:
https://github.com/getsentry/sentry-fastlane-plugin/pull/144
The referenced PR takes the created/updated PR, downloads the current sentry-cli macOS & windows binaries and commits them in the PR created by this workflow.
It does not use the `url` and `base branch` outputs, but i left those as they might be useful for other approaches.
=> Add Outputs to Update Workflow

.github/workflows/updater.yml, CHANGELOG.md, scripts/update-changelog.ps1, tests/testdata/changelog/new-second-section/CHANGELOG.md.expected, tests/testdata/changelog/new-second-section/CHANGELOG.md.original, tests/testdata/changelog/new/CHANGELOG.md.expected, tests/testdata/changelog/new/CHANGELOG.md.original, tests/testdata/changelog/update/CHANGELOG.md.expected, tests/testdata/changelog/update/CHANGELOG.md.original, tests/update-changelog.ps1
overridable by `changelog-section` input
closes #17
=> Change the changelog section header to Dependencies

scripts/update-changelog.ps1, tests/testdata/changelog/new-second-section/CHANGELOG.md.expected, tests/testdata/changelog/update/CHANGELOG.md.expected, tests/testdata/changelog/update/CHANGELOG.md.original
=> fix: preserve changelog bullet point

.github/workflows/updater.yml, .github/workflows/workflow-tests.yml, README.md
=> feat: add pr-strategy switch

CHANGELOG.md, danger/dangerfile.js
We can't post to the PR in that case.
Also see the PR where I've tested this: #38
=> fix: show GH annotations when running from forks

CHANGELOG.md, danger/CONTRIBUTING.md, danger/dangerfile.js
In response to https://github.com/getsentry/sentry-java/issues/1442 - actions should be pinned to reduce attack surface.
=> feat: Danger - check for unpinned actions

CHANGELOG.md, danger/dangerfile.js
=> feat: verify Changelog entry is not added to a released section

CHANGELOG.md, danger/dangerfile.js
See https://github.com/getsentry/sentry-cocoa/pull/2789
=> chore: add "github" to the list of danger action-check whitelist users

.github/workflows/updater.yml, CHANGELOG.md, updater/tests/nonbot-commits.ps1
- chore: updater deps
- chore: update changelog
=> deps: update updater action dependencies

CHANGELOG.md, updater/scripts/nonbot-commits.ps1, updater/tests/nonbot-commits.ps1
fixes: #56 - the issue was with `git@` SSH repo URLs - git doesn't have permissions and failed.
This has gone unnoticed because of pwsh behaviour of ignoring native commands exit code (Hopefully, this will change in the future, see https://github.com/actions/runner-images/issues/8900), `git` in this case.
=> fix: updater SSH repos nonbot commits

updater/tests/get-changelog.ps1
#skip-changelog
This kept breaking whenever there was a change in another repo
=> test: avoid depending on external repo changelog contents

CHANGELOG.md, danger/dangerfile.js
This was an issue with there was another link in the changelog that had the same number as the current PR.
Reported by @romtsn on Discord
> e.g. I've opened a new PR with id 643 https://github.com/getsentry/sentry-android-gradle-plugin/blob/fed6ae5645b62abbeea32354b74d623e01b7294c/CHANGELOG.md?plain=1#L10, but there's already an entry #643 which references the sentry-java repo and hence it fails https://github.com/getsentry/sentry-android-gradle-plugin/blob/fed6ae5645b62abbeea32354b74d623e01b7294c/CHANGELOG.md?plain=1#L447
=> fix: Danger - recognize PR links based on full URL instead of just the PR number.

.github/workflows/updater.yml, CHANGELOG.md
To fix an issue caused by GH API change. See https://github.com/peter-evans/create-pull-request/issues/2790 for details.
=> chore: update create PR action to v6.0.1

.github/workflows/updater.yml, CHANGELOG.md
The octokit action is outdated and the team doesn't seem to maintain it & release the node20 update. https://github.com/octokit/request-action/issues/272
We don't actually need it all that much so let's use `gh` instead.
=> chore: remove octokit action dependency

CHANGELOG.md, updater/scripts/common.ps1, updater/scripts/sort-versions.ps1, updater/scripts/update-dependency.ps1, updater/tests/sort-versions.ps1, updater/tests/update-dependency.ps1
Add support to parse prerelease semantic versions so that when developers update manually to a prerelease, we can recognize it and not roll back to the latest stable release matching the pattern
=> fix: support proper sorting for prereleases

CHANGELOG.md, updater/scripts/get-changelog.ps1, updater/tests/get-changelog.Tests.ps1
=> fix: get-changelog support for cross-repo links

CHANGELOG.md, updater/scripts/get-changelog.ps1, updater/tests/get-changelog.Tests.ps1
=> fix: truncate changelog to nearest SemVer even if actual previous version is missing

updater/tests/get-changelog.Tests.ps1
This got broken by [an unlucky change](https://github.com/getsentry/sentry-native/commit/4ebdbe900a085c0a97f8ef52edeeef04bf715da6#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR43) in an old sentry-native changelog item we rely on in our tests...
#skip-changelog
=> chore: Update get-changelog.Tests.ps1

CHANGELOG.md, danger/dangerfile.js
This allows skipping the danger changelog check with a `skip-changelog` label in addition to `#skip-changelog` in the PR description.
To make sure this triggers properly, the `danger` workflow should be run on a PR being `labeled` and `unlabeled`.
Closes #93.
Please feel free to close this if this functionality isn't desired.
=> feat(danger): Allow skipping changelog with label

README.md
The example should mention `labeled` and `unlabeled`.
#skip-changelog
=> fix(readme): Adjust danger template for #94

CHANGELOG.md, sentry-cli/integration-test/tests/action.Tests.ps1
There was a section for the proguard mapping test already, so I added the proguard endpoint to that test. Not sure if it's good enough 🤔
=> test: Add proguard endpoint in sentry-server test
